server:
  port: 9090

spring:

  application:
    name: @project.name@

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@