server:
  port: 9090

spring:

  application:
    name: events-api

info:
  build:
    artifact: events-api
    name: events-api
    description: Russia 2018 FIFA World Cup Events API
    version: 1.0.0